name: adventures_in_chat_app
description: A Flutter chat app for Adventures In Flutter.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider:
  firebase_core:
  firebase_auth:
  google_sign_in:
  sign_in_with_apple:
  flutter_auth_buttons:
  cloud_firestore:
  # TODO: change when https://github.com/flutter/flutter/issues/21421 is fixed  
  firebase_messaging:
    git:
      url: git://github.com/preetjdp/flutterfire.git
      ref: fix-3312
      path: packages/firebase_messaging

dev_dependencies:
  test:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  mockito:
  flutter_launcher_icons:

flutter:
  assets:
    - assets/images/
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
