name: adventures_in_chat_app
description: A Flutter chat app for Adventures In Flutter.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider:
  firebase_core:
  firebase_auth:
  flutter_facebook_login:
  google_sign_in:
  apple_sign_in:
  flutter_auth_buttons:
  cloud_firestore:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true