name: Mobile Apps

on:
  pull_request:
    branches:
      - test
  push:
    branches:
      - test
      - build

jobs:
  build:
    name: CI
    runs-on: macOS-latest
    steps:
    # several actions use checkout 
    # docs in flutter-action say to use v1 but we should try to upgrade to v2 at some point 
    - uses: actions/checkout@v1
    
    ##############################################
    # flutter-action
    ##############################################
    # the flutter-action action seems to need java
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    # use flutter-action configured with flutter channel
    - uses: subosito/flutter-action@v1
      with:
        channel: 'dev' # or: 'stable' or 'beta'

    - run: flutter pub get
    
    ##############################################
    # run tests and upload coverage
    ##############################################
    - name: Run tests and save coverage
      # run on PR for status check and on push for coverage
      if: ${{ github.base_ref == 'refs/heads/test' || github.ref == 'refs/heads/test' }}
      run: flutter test --coverage

    - name: Coveralls
      # run on push to test branch, for the coverage
      if: github.ref == 'refs/heads/test'
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    ##############################################
    # setup-gcloud
    ##############################################
    # the setup-gcloud action seems to need python
    - uses: actions/setup-python@v1
      if: github.event_name == 'pull_request'
      with:
        python-version: '3.x'
    # use setup-gcloud configured with auth credentials 
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      if: github.event_name == 'pull_request'
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.GCS_EMAIL }}
        service_account_key: ${{ secrets.GCS_KEY }}
    
    ############################################
    # download credential files 
    ############################################
    - name: Download credential files
      if: github.ref == 'refs/heads/build'
      run: ./get-credentials.sh
      
    ##############################################
    # build android, build ios  to coveralls.io
    ##############################################
    - name: Build Android
      if: github.ref == 'refs/heads/build'
      run: flutter build appbundle --build-number=$GITHUB_RUN_NUMBER
    
    - name: Build iOS
      if: github.ref == 'refs/heads/build'
      run: flutter build ios --release --no-codesign --build-number=$GITHUB_RUN_NUMBER