name: Mobile Apps

on:
  pull_request:
    branches:
      - test
  push:
    branches:
      - test

jobs:
  build:
    name: CI
    runs-on: macOS-latest
    steps:
    # several actions use checkout 
    # docs in flutter-action say to use v1 but we should try to upgrade to v2 at some point 
    - uses: actions/checkout@v1
    
    ##############################################
    # flutter-action
    ##############################################
    # the flutter-action action seems to need java
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    # use flutter-action configured with flutter channel
    - uses: subosito/flutter-action@v1
      with:
        channel: 'test' # or: 'stable' or 'beta'
    
    ##############################################
    # setup-gcloud
    ##############################################
    # the setup-gcloud action seems to need python
    - uses: actions/setup-python@v1
      if: github.event_name == 'pull_request'
      with:
        python-version: '3.x'
    # use setup-gcloud configured with auth credentials 
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      if: github.event_name == 'pull_request'
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.GCS_EMAIL }}
        service_account_key: ${{ secrets.GCS_KEY }}
    
    ############################################
    # download credential files 
    ############################################
    - name: Download credential files
      if: github.event_name == 'pull_request'
      run: ./get-credentials.sh
    
    ##############################################
    # run tests, build android, build ios
    ##############################################
    - run: flutter pub get
    - run: flutter test --coverage
    
    - name: Build Android
      if: github.event_name == 'pull_request'
      run: flutter build appbundle --build-number=$GITHUB_RUN_NUMBER
    
    - name: Build iOS
      if: github.event_name == 'pull_request'
      run: flutter build ios --release --no-codesign --build-number=$GITHUB_RUN_NUMBER

    ##############################################
    # upload coverage to coveralls.io
    ##############################################
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}